// GENERATED by scripts/sync-expressions.mjs — DO NOT EDIT BY HAND.
// Expression defaults are the LIVE hand-tuned exp3 files (§3 of the manual).
// Re-run: node scripts/sync-expressions.mjs <assetsDir>  to refresh.
export const EXPRESSIONS = {
  "ask": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.721,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -9.592,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": 10,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleZ",
        "Value": -21.224,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleY",
        "Value": -0.204,
        "Blend": "Add"
      }
    ]
  },
  "browser": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 0.5,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 0.5,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.4,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": 0.3,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": 0.2,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 0.2,
        "Blend": "Overwrite"
      }
    ]
  },
  "celebrate": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamCheek",
        "Value": 0.6,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeLSmile",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeRSmile",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 1,
        "Blend": "Overwrite"
      }
    ]
  },
  "done": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeROpen",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeLOpen",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeLSmile",
        "Value": 1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeRSmile",
        "Value": 1,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 1,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthForm",
        "Value": 1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLY",
        "Value": 0.851,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 0.731,
        "Blend": "Add"
      }
    ]
  },
  "drag": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": -0.343,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeLSmile",
        "Value": 1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeRSmile",
        "Value": 1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": -0.343,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.746,
        "Blend": "Add"
      }
    ]
  },
  "failed": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowRY",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -0.97,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": 0,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": -0.761,
        "Blend": "Add"
      }
    ]
  },
  "grin": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeLSmile",
        "Value": 0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeRSmile",
        "Value": 0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.6,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": 10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -6.259,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": -2.177,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleY",
        "Value": -17.347,
        "Blend": "Add"
      }
    ]
  },
  "idle": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": -0.1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": -0.1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLY",
        "Value": 0.6,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -0.15,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": 0.3,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": 0.1,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.5,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": 0.3,
        "Blend": "Add"
      }
    ]
  },
  "knit": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowLY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": 0.5,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": 0.5,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -10,
        "Blend": "Add"
      }
    ]
  },
  "pout": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowLY",
        "Value": -0.97,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": -0.76,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -1,
        "Blend": "Overwrite"
      }
    ]
  },
  "raise": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowLY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 0.088,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.3,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamAngleZ",
        "Value": 0.408,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleY",
        "Value": -17.347,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleX",
        "Value": -17.551,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -7.551,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": -1.565,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": -2.517,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": 0.19,
        "Blend": "Add"
      }
    ]
  },
  "read": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowLY",
        "Value": 0.4,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 0.4,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.235,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamAngleY",
        "Value": -22.857,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleX",
        "Value": 2.041,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleZ",
        "Value": 1.429,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -5.918,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": -3.469,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": -10,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeLOpen",
        "Value": -0.25,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeLSmile",
        "Value": 0,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": -0.25,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeRSmile",
        "Value": 0,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": -0.2,
        "Blend": "Add"
      }
    ]
  },
  "search": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowLY",
        "Value": 0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": 0.4,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.3,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamAngleY",
        "Value": -15.918,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": 10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": 10,
        "Blend": "Add"
      }
    ]
  },
  "sleepy": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 0.72,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 0.72,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -0.2,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -0.2,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamAngleZ",
        "Value": -30,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleX",
        "Value": -30,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": 1,
        "Blend": "Add"
      }
    ]
  },
  "smile": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeLSmile",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeRSmile",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.18,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamAngleY",
        "Value": -30,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleZ",
        "Value": 5.918,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": -10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -1.224,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": -10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": -1,
        "Blend": "Add"
      }
    ]
  },
  "surprise": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.714,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": 10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -10,
        "Blend": "Add"
      }
    ]
  },
  "think": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": -0.204,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": -0.367,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleX",
        "Value": -7.143,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleY",
        "Value": -14.082,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleZ",
        "Value": -1.02,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": 10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": 8.571,
        "Blend": "Add"
      }
    ]
  },
  "think_closed": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -0.8,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.228,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamAngleY",
        "Value": -1.837,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleZ",
        "Value": -30,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": 1.565,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": -10,
        "Blend": "Add"
      }
    ]
  },
  "thinking": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowLY",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": -1,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": 0.5,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": 0.5,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.8,
        "Blend": "Add"
      }
    ]
  },
  "tilt": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamAngleZ",
        "Value": 20,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -0.2,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -0.2,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.3,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeLOpen",
        "Value": -0.3,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": -0.3,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLX",
        "Value": 0,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallY",
        "Value": 1,
        "Blend": "Add"
      }
    ]
  },
  "tool": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamBrowLY",
        "Value": 0.9,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 0.4,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.3,
        "Blend": "Add"
      }
    ]
  },
  "tsundere": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamEyeLOpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": 1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.163,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.381,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBodyAngleX",
        "Value": -5.782,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": 10,
        "Blend": "Add"
      },
      {
        "Id": "ParamAngleY",
        "Value": 0,
        "Blend": "Add"
      }
    ]
  },
  "waiting": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamAngleZ",
        "Value": 14.516,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLY",
        "Value": 0.8,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRY",
        "Value": 0.3,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowLAngle",
        "Value": -0.2,
        "Blend": "Add"
      },
      {
        "Id": "ParamBrowRAngle",
        "Value": -0.3,
        "Blend": "Add"
      },
      {
        "Id": "ParamMouthForm",
        "Value": -0.4,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeBallX",
        "Value": 0.35,
        "Blend": "Add"
      }
    ]
  },
  "write": {
    "Type": "Live2D Expression",
    "Parameters": [
      {
        "Id": "ParamMouthForm",
        "Value": -1,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowLY",
        "Value": -0.3,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBrowRY",
        "Value": -0.3,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamMouthOpenY",
        "Value": 0.779,
        "Blend": "Overwrite"
      },
      {
        "Id": "ParamBodyAngleY",
        "Value": -10,
        "Blend": "Add"
      },
      {
        "Id": "ParamBodyAngleZ",
        "Value": 10,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeLOpen",
        "Value": -0.33,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeLSmile",
        "Value": 0,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeROpen",
        "Value": -0.33,
        "Blend": "Add"
      },
      {
        "Id": "ParamEyeRSmile",
        "Value": 0,
        "Blend": "Add"
      }
    ]
  }
}
